x-veld:
  code:
    description: "hard-coded conversion of apis ner models to custom json format."
    topic:
      - "ETL"
      - "Data Cleaning"

    input:
      - volume: /veld/input/
        description: "This input is hard-wired to the apis spacy-ner repo and not made for generic
          usage."
        file_type:
          - "pickle"
          - "txt"
          - "json"
        content: "NER gold data"

    output:
      - volume: /veld/output/cleaned/
        environment_var: out_json_cleaned_file
        description: "raw uncleaned, as it was originally. Now just transformed to json."
        file_type: "json"
        content: "NER gold data"
      - volume: /veld/output/uncleaned/
        environment_var: out_json_uncleaned_file
        description: "removed empty entity annotations and fixed border issues."
        file_type: "json"
        content: "NER gold data"
      - volume: /veld/output/cleaned_simplified/
        environment_var: out_json_cleaned_simplified_file
        description: "additionally to cleaning, this data is slimmed down from superfluous entity 
          ids in favor of simplified entity classes."
        file_type: "json"
        content: "NER gold data"
      - volume: /veld/output/log/
        environment_var: out_log_file
        file_type: "txt"

services:
  veld:
    build: .
    command: python /veld/code/extract_and_clean.py
    volumes:
      - ./src/:/veld/code/
    environment:
      out_json_uncleaned_file: null
      out_json_cleaned_file: null
      out_json_cleaned_simplified_file: null
      out_log_file: null

